apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-resources
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"

##container will be created as resources/limits defined